import Foundation

/// Generates a .mobileconfig configuration profile carrying a
/// com.apple.dnsSettings.managed payload (system-wide encrypted DNS).
/// Installing it in Settings gives ad blocking with the VPN off — the two
/// modes are mutually exclusive by OS precedence (an active VPN's DNS wins).
public enum MobileConfigBuilder {

    public static func profile(for preset: DNSProviderPreset, organization: String = "IBlocker") -> Data {
        let payloadUUID = stableUUID("payload." + preset.id)
        let profileUUID = stableUUID("profile." + preset.id)

        var dnsSettings = ""
        switch preset.transport {
        case .https:
            dnsSettings += "\t\t\t\t<key>DNSProtocol</key>\n\t\t\t\t<string>HTTPS</string>\n"
            if let url = preset.serverURL {
                dnsSettings += "\t\t\t\t<key>ServerURL</key>\n\t\t\t\t<string>\(xmlEscape(url))</string>\n"
            }
        case .tls:
            dnsSettings += "\t\t\t\t<key>DNSProtocol</key>\n\t\t\t\t<string>TLS</string>\n"
            if let name = preset.serverName {
                dnsSettings += "\t\t\t\t<key>ServerName</key>\n\t\t\t\t<string>\(xmlEscape(name))</string>\n"
            }
        }
        if !preset.addresses.isEmpty {
            dnsSettings += "\t\t\t\t<key>ServerAddresses</key>\n\t\t\t\t<array>\n"
            for address in preset.addresses {
                dnsSettings += "\t\t\t\t\t<string>\(xmlEscape(address))</string>\n"
            }
            dnsSettings += "\t\t\t\t</array>\n"
        }

        let xml = """
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
        \t<key>PayloadContent</key>
        \t<array>
        \t\t<dict>
        \t\t\t<key>PayloadType</key>
        \t\t\t<string>com.apple.dnsSettings.managed</string>
        \t\t\t<key>PayloadIdentifier</key>
        \t\t\t<string>com.iblocker.dns.\(preset.id)</string>
        \t\t\t<key>PayloadUUID</key>
        \t\t\t<string>\(payloadUUID)</string>
        \t\t\t<key>PayloadVersion</key>
        \t\t\t<integer>1</integer>
        \t\t\t<key>PayloadDisplayName</key>
        \t\t\t<string>\(xmlEscape(preset.name)) DNS</string>
        \t\t\t<key>DNSSettings</key>
        \t\t\t<dict>
        \(dnsSettings)\t\t\t</dict>
        \t\t\t<key>ProhibitDisablement</key>
        \t\t\t<false/>
        \t\t</dict>
        \t</array>
        \t<key>PayloadDisplayName</key>
        \t<string>IBlocker — \(xmlEscape(preset.name))</string>
        \t<key>PayloadDescription</key>
        \t<string>Encrypted DNS (\(xmlEscape(preset.detail))). Generated by IBlocker.</string>
        \t<key>PayloadIdentifier</key>
        \t<string>com.iblocker.profile.\(preset.id)</string>
        \t<key>PayloadOrganization</key>
        \t<string>\(xmlEscape(organization))</string>
        \t<key>PayloadRemovalDisallowed</key>
        \t<false/>
        \t<key>PayloadType</key>
        \t<string>Configuration</string>
        \t<key>PayloadUUID</key>
        \t<string>\(profileUUID)</string>
        \t<key>PayloadVersion</key>
        \t<integer>1</integer>
        </dict>
        </plist>
        """
        return Data(xml.utf8)
    }

    /// Deterministic UUID derived from the seed, so re-exporting the same
    /// preset produces an identical profile (Settings treats it as an update,
    /// not a duplicate). Not an RFC 4122 name-based UUID, just stable.
    static func stableUUID(_ seed: String) -> String {
        let h1 = FNV1a.hash64("iblocker.uuid.a:" + seed)
        let h2 = FNV1a.hash64("iblocker.uuid.b:" + seed)
        var bytes = [UInt8]()
        for shift in stride(from: 56, through: 0, by: -8) {
            bytes.append(UInt8((h1 >> UInt64(shift)) & 0xFF))
        }
        for shift in stride(from: 56, through: 0, by: -8) {
            bytes.append(UInt8((h2 >> UInt64(shift)) & 0xFF))
        }
        bytes[6] = (bytes[6] & 0x0F) | 0x40
        bytes[8] = (bytes[8] & 0x3F) | 0x80
        let hex = bytes.map { String(format: "%02X", $0) }.joined()
        var s = hex
        var parts: [String] = []
        for length in [8, 4, 4, 4, 12] {
            parts.append(String(s.prefix(length)))
            s = String(s.dropFirst(length))
        }
        return parts.joined(separator: "-")
    }

    static func xmlEscape(_ string: String) -> String {
        string
            .replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
    }
}
